name: Build beta versions

on:
  push:
    branches:
        - '*'        # Matches all branches
        - '!master'  # Excludes master branch

env:
  PLUGIN_NAME: bibtex-manager

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "21.x"

      - name: Build
        run: |
          yarn
          yarn run build --if-present
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          ls

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLUGIN_NAME }}-artifacts
          path: |
            ${{ env.PLUGIN_NAME }}/
            ${{ env.PLUGIN_NAME }}.zip
            main.js
            manifest.json
            styles.css

